import 'dart:collection';

import 'package:dex_team_builder/models/pokemon_species.dart';
import 'package:flutter/material.dart';

class PokemonSpeciesRepository extends ChangeNotifier {
  List<PokemonSpecies> _pokemonSpecies = [];

  UnmodifiableListView<PokemonSpecies> get pokemonSpecies =>
      UnmodifiableListView(_pokemonSpecies);

  PokemonSpeciesRepository() {
    _pokemonSpecies = [
      PokemonSpecies(
        id: 1,
        name: "bulbasaur",
        types: ["grass", "poison"],
        possibleMoves: [
          "Leaf Blade",
          "Poisonpowder",
          "Sleep Powder",
          "Tackle",
          "Solarbeam", 
          "Giga Drain"
        ],
      ),
      PokemonSpecies(
        id: 2,
        name: "ivysaur",
        types: ["grass", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 3,
        name: "venusaur",
        types: ["grass", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 4,
        name: "charmander",
        types: ["fire"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 5,
        name: "charmeleon",
        types: ["fire"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 6,
        name: "charizard",
        types: ["fire", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 7,
        name: "squirtle",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 8,
        name: "wartortle",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 9,
        name: "blastoise",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 10,
        name: "caterpie",
        types: ["bug"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 11,
        name: "metapod",
        types: ["bug"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 12,
        name: "butterfree",
        types: ["bug", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 13,
        name: "weedle",
        types: ["bug", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 14,
        name: "kakuna",
        types: ["bug", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 15,
        name: "beedrill",
        types: ["bug", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 16,
        name: "pidgey",
        types: ["normal", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 17,
        name: "pidgeotto",
        types: ["normal", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 18,
        name: "pidgeot",
        types: ["normal", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 19,
        name: "rattata",
        types: ["normal"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 20,
        name: "raticate",
        types: ["normal"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 21,
        name: "spearow",
        types: ["normal", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 22,
        name: "fearow",
        types: ["normal", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 23,
        name: "ekans",
        types: ["poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 24,
        name: "arbok",
        types: ["poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 25,
        name: "pikachu",
        types: ["electric"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 26,
        name: "raichu",
        types: ["electric"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 27,
        name: "sandshrew",
        types: ["ground"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 28,
        name: "sandslash",
        types: ["ground"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 29,
        name: "nidoran-f",
        types: ["poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 30,
        name: "nidorina",
        types: ["poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 31,
        name: "nidoqueen",
        types: ["poison", "ground"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 32,
        name: "nidoran-m",
        types: ["poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 33,
        name: "nidorino",
        types: ["poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 34,
        name: "nidoking",
        types: ["poison", "ground"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 35,
        name: "clefairy",
        types: ["fairy"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 36,
        name: "clefable",
        types: ["fairy"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 37,
        name: "vulpix",
        types: ["fire"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 38,
        name: "ninetales",
        types: ["fire"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 39,
        name: "jigglypuff",
        types: ["fairy"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 40,
        name: "wigglytuff",
        types: ["fairy"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 41,
        name: "zubat",
        types: ["poison", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 42,
        name: "golbat",
        types: ["poison", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 43,
        name: "oddish",
        types: ["poison", "grass"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 44,
        name: "gloom",
        types: ["poison", "grass"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 45,
        name: "vileplume",
        types: ["poison", "grass"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 46,
        name: "paras",
        types: ["bug", "grass"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 47,
        name: "parasect",
        types: ["bug", "grass"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 48,
        name: "venonat",
        types: ["bug", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 49,
        name: "venomoth",
        types: ["bug", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 50,
        name: "diglett",
        types: ["ground"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 51,
        name: "dugtrio",
        types: ["ground"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 52,
        name: "meowth",
        types: ["normal"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 53,
        name: "persian",
        types: ["normal"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 54,
        name: "psyduck",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 55,
        name: "golduck",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 56,
        name: "mankey",
        types: ["fighting"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 57,
        name: "primeape",
        types: ["fighting"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 58,
        name: "growlithe",
        types: ["fire"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 59,
        name: "arcanine",
        types: ["fire"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 60,
        name: "poliwag",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 61,
        name: "poliwhirl",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 62,
        name: "poliwrath",
        types: ["water", "fighting"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 63,
        name: "abra",
        types: ["psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 64,
        name: "kadabra",
        types: ["psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 65,
        name: "alakazam",
        types: ["psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 66,
        name: "machop",
        types: ["fighting"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 67,
        name: "machoke",
        types: ["fighting"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 68,
        name: "machamp",
        types: ["fighting"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 69,
        name: "bellsprout",
        types: ["grass", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 70,
        name: "weepinbell",
        types: ["grass", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 71,
        name: "victreebel",
        types: ["grass", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 72,
        name: "tentacool",
        types: ["water", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 73,
        name: "tentacruel",
        types: ["water", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 74,
        name: "geodude",
        types: ["ground", "rock"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 75,
        name: "graveler",
        types: ["ground", "rock"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 76,
        name: "golem",
        types: ["ground", "rock"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 77,
        name: "ponyta",
        types: ["fire"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 78,
        name: "rapidash",
        types: ["fire"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 79,
        name: "slowpoke",
        types: ["water", "psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 80,
        name: "slowbro",
        types: ["water", "psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 81,
        name: "magnemite",
        types: ["electric", "steel"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 82,
        name: "magneton",
        types: ["electric", "steel"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 83,
        name: "farfetchd",
        types: ["normal", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 84,
        name: "doduo",
        types: ["normal", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 85,
        name: "dodrio",
        types: ["normal", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 86,
        name: "seel",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 87,
        name: "dewgong",
        types: ["water", "ice"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 88,
        name: "grimer",
        types: ["poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 89,
        name: "muk",
        types: ["poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 90,
        name: "shellder",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 91,
        name: "cloyster",
        types: ["water", "ice"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 92,
        name: "gastly",
        types: ["ghost", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 93,
        name: "haunter",
        types: ["ghost", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 94,
        name: "gengar",
        types: ["ghost", "poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 95,
        name: "onix",
        types: ["ground", "rock"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 96,
        name: "drowzee",
        types: ["psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 97,
        name: "hypno",
        types: ["psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 98,
        name: "krabby",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 99,
        name: "kingler",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 100,
        name: "voltorb",
        types: ["electric"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 101,
        name: "electrode",
        types: ["electric"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 102,
        name: "exeggcute",
        types: ["grass", "psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 103,
        name: "exeggutor",
        types: ["grass", "psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 104,
        name: "cubone",
        types: ["ground"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 105,
        name: "marowak",
        types: ["ground"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 106,
        name: "hitmonlee",
        types: ["fighting"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 107,
        name: "hitmonchan",
        types: ["fighting"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 108,
        name: "lickitung",
        types: ["normal"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 109,
        name: "koffing",
        types: ["poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 110,
        name: "weezing",
        types: ["poison"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 111,
        name: "rhyhorn",
        types: ["rock", "ground"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 112,
        name: "rhydon",
        types: ["rock", "ground"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 113,
        name: "chansey",
        types: ["normal"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 114,
        name: "tangela",
        types: ["grass"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 115,
        name: "kangaskhan",
        types: ["normal"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 116,
        name: "horsea",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 117,
        name: "seadra",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 118,
        name: "goldeen",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 119,
        name: "seaking",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 120,
        name: "staryu",
        types: ["water", "psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 121,
        name: "starmie",
        types: ["water", "psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 122,
        name: "mr-mime",
        types: ["psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 123,
        name: "scyther",
        types: ["big", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 124,
        name: "jynx",
        types: ["ice", "psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 125,
        name: "electabuzz",
        types: ["electric"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 126,
        name: "magmar",
        types: ["fire"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 127,
        name: "pinsir",
        types: ["bug"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 128,
        name: "tauros",
        types: ["normal"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 129,
        name: "magikarp",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 130,
        name: "gyarados",
        types: ["water", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 131,
        name: "lapras",
        types: ["water", "ice"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 132,
        name: "ditto",
        types: ["normal"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 133,
        name: "eevee",
        types: ["normal"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 134,
        name: "vaporeon",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 135,
        name: "jolteon",
        types: ["electric"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 136,
        name: "flareon",
        types: ["fire"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 137,
        name: "porygon",
        types: ["normal"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 138,
        name: "omanyte",
        types: ["water", "rock"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 139,
        name: "omastar",
        types: ["water", "rock"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 140,
        name: "kabuto",
        types: ["water", "rock"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 141,
        name: "kabutops",
        types: ["water", "rock"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 142,
        name: "aerodactyl",
        types: ["flying", "rock"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 143,
        name: "snorlax",
        types: ["water"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 144,
        name: "articuno",
        types: ["ice", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 145,
        name: "zapdos",
        types: ["electric", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 146,
        name: "moltres",
        types: ["fire", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 147,
        name: "dratini",
        types: ["dragon"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 148,
        name: "dragonair",
        types: ["dragon"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 149,
        name: "dragonite",
        types: ["dragon", "flying"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 150,
        name: "mewtwo",
        types: ["psychic"],
        possibleMoves: [],
      ),
      PokemonSpecies(
        id: 151,
        name: "mew",
        types: ["psychic"],
        possibleMoves: [],
      ),
    ];
  }
}
