// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1wf0JWTfFOZ1N6dRAgKHHSWXTrtn-Cko',
    appId: '1:424445161953:web:11ae606726871b24eb62a0',
    messagingSenderId: '424445161953',
    projectId: 'dex-team-builder',
    authDomain: 'dex-team-builder.firebaseapp.com',
    storageBucket: 'dex-team-builder.appspot.com',
    measurementId: 'G-D5CB5N1JXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD39mcAi_QsMyH-naaCNW8gRet7-wcuJmU',
    appId: '1:424445161953:android:5b40921fb5227acceb62a0',
    messagingSenderId: '424445161953',
    projectId: 'dex-team-builder',
    storageBucket: 'dex-team-builder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKybCz1y7wglLziphjtVlKYn9nU9v6zLY',
    appId: '1:424445161953:ios:b6a6101d39ec8c64eb62a0',
    messagingSenderId: '424445161953',
    projectId: 'dex-team-builder',
    storageBucket: 'dex-team-builder.appspot.com',
    iosClientId: '424445161953-70sgjv49jjvv13fjaa5qt9ofj35fjpcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dexTeamBuilder',
  );
}
